# **Market Basket Analysis using ECLAT**

**Importing Dependencies**

In [2]:
import numpy as np
import pandas as pd
from apyori import apriori

**---- INITIAL DATA ANALYSIS & PRE PROCESSING ----**

In [3]:
dataset = pd.read_csv('Groceries_dataset.csv') #reading the dataset

In [4]:
dataset.head() #gives top 5 rows

   Member_number        Date   itemDescription
0           1808  21-07-2015    tropical fruit
1           2552  05-01-2015        whole milk
2           2300  19-09-2015         pip fruit
3           1187  12-12-2015  other vegetables
4           3037  01-02-2015        whole milk

In [5]:
dataset.shape #dimensions of the dataset

(38765, 3)

In [6]:
dataset.info() #information about the dataset

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38765 entries, 0 to 38764
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Member_number    38765 non-null  int64
 1   Date             38765 non-null  object
 2   itemDescription  38765 non-null  object
dtypes: int64(1), object(2)
memory usage: 908.7+ KB

In [7]:
dataset.describe() #statistical description about the dataset

       Member_number
count   38765.000000
mean     3003.641868
std      1153.611031
min      1000.000000
25%      2002.000000
50%      3005.000000
75%      4007.000000
max      5000.000000

**Creating transactions needed for ECLAT analysis**

In [8]:
transactions = dataset.groupby(['Member_number', 'Date'])['itemDescription'].apply(list).values.tolist()

**Analysis of the above operation**

In [9]:
for i in range(5):
    print(transactions[i])

['sausage', 'whole milk', 'semi-finished bread', 'yogurt']
['whole milk', 'pastry', 'salty snack']
['canned beer', 'misc. beverages']
['sausage', 'hygiene articles']
['soda', 'pickled vegetables']

**Definig rules and training the model**

In [10]:
frequent_itemsets = apriori(transactions, min_support=0.001, min_confidence=0.1, min_lift=0.5, min_length=2) #defining thresholds

**Model Results**

In [11]:
rules = list(frequent_itemsets) #output
for i, (rule) in enumerate(rules):
    if i == 50:
        break
    print(rule)

RelationRecord(items=frozenset({'other vegetables'}), support=0.12210118291786407, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'other vegetables'}), confidence=0.12210118291786407, lift=1.0)])
RelationRecord(items=frozenset({'rolls/buns'}), support=0.11000467820624206, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'rolls/buns'}), confidence=0.11000467820624206, lift=1.0)])
RelationRecord(items=frozenset({'whole milk'}), support=0.15792287642852368, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'whole milk'}), confidence=0.15792287642852368, lift=1.0)])
RelationRecord(items=frozenset({'other vegetables', 'UHT-milk'}), support=0.002138608567800575, ordered_statistics=[OrderedStatistic(items_base=frozenset({'UHT-milk'}), items_add=frozenset({'other vegetables'}), confidence=0.1, lift=0.818992884510126)])
RelationRecord(items=frozenset({'whole milk', 'UHT-milk'}), support=0.0025395976742631824, ordered_statistics=[OrderedStatistic(items_base=frozenset({'UHT-milk'}), items_add=frozenset({'whole milk'}), confidence=0.11875, lift=0.7519493228946255)])
RelationRecord(items=frozenset({'whole milk', 'beef'}), support=0.004678206242063757, ordered_statistics=[OrderedStatistic(items_base=frozenset({'beef'}), items_add=frozenset({'whole milk'}), confidence=0.1377952755905512, lift=0.8725479088706803)])
RelationRecord(items=frozenset({'other vegetables', 'berries'}), support=0.0026732607097507185, ordered_statistics=[OrderedStatistic(items_base=frozenset({'berries'}), items_add=frozenset({'other vegetables'}), confidence=0.12269938650306748, lift=1.0048992447977005)])
RelationRecord(items=frozenset({'whole milk', 'berries'}), support=0.0022722716032881106, ordered_statistics=[OrderedStatistic(items_base=frozenset({'berries'}), items_add=frozenset({'whole milk'}), confidence=0.10429447852760736, lift=0.660414000088273)])
RelationRecord(items=frozenset({'other vegetables', 'beverages'}), support=0.0017376194613379669, ordered_statistics=[OrderedStatistic(items_base=frozenset({'beverages'}), items_add=frozenset({'other vegetables'}), confidence=0.10483870967741936, lift=0.8586215724702932)])
RelationRecord(items=frozenset({'soda', 'beverages'}), support=0.001871282496825503, ordered_statistics=[OrderedStatistic(items_base=frozenset({'beverages'}), items_add=frozenset({'soda'}), confidence=0.11290322580645162, lift=1.1626778855760054)])
RelationRecord(items=frozenset({'whole milk', 'beverages'}), support=0.0019381140145692708, ordered_statistics=[OrderedStatistic(items_base=frozenset({'beverages'}), items_add=frozenset({'whole milk'}), confidence=0.11693548387096775, lift=0.7404594351084598)])
RelationRecord(items=frozenset({'other vegetables', 'bottled beer'}), support=0.004678206242063757, ordered_statistics=[OrderedStatistic(items_base=frozenset({'bottled beer'}), items_add=frozenset({'other vegetables'}), confidence=0.10324483775811208, lift=0.8455678748629617)])
RelationRecord(items=frozenset({'whole milk', 'bottled beer'}), support=0.007150972398583172, ordered_statistics=[OrderedStatistic(items_base=frozenset({'bottled beer'}), items_add=frozenset({'whole milk'}), confidence=0.15781710914454278, lift=0.9993302598941151)])
RelationRecord(items=frozenset({'bottled water', 'whole milk'}), support=0.007150972398583172, ordered_statistics=[OrderedStatistic(items_base=frozenset({'bottled water'}), items_add=frozenset({'whole milk'}), confidence=0.11784140969162996, lift=0.7461959429605837)])
RelationRecord(items=frozenset({'brown bread', 'whole milk'}), support=0.004477711688832453, ordered_statistics=[OrderedStatistic(items_base=frozenset({'brown bread'}), items_add=frozenset({'whole milk'}), confidence=0.11900532859680285, lift=0.7535661158671016)])
RelationRecord(items=frozenset({'whole milk', 'butter'}), support=0.004678206242063757, ordered_statistics=[OrderedStatistic(items_base=frozenset({'butter'}), items_add=frozenset({'whole milk'}), confidence=0.13282732447817835, lift=0.84108982486965)])
RelationRecord(items=frozenset({'candy', 'rolls/buns'}), support=0.0014702933903628951, ordered_statistics=[OrderedStatistic(items_base=frozenset({'candy'}), items_add=frozenset({'rolls/buns'}), confidence=0.10232558139534884, lift=0.9301929978241826)])
RelationRecord(items=frozenset({'whole milk', 'candy'}), support=0.002138608567800575, ordered_statistics=[OrderedStatistic(items_base=frozenset({'candy'}), items_add=frozenset({'whole milk'}), confidence=0.1488372093023256, lift=0.942467694790816)])
RelationRecord(items=frozenset({'whole milk', 'canned beer'}), support=0.006014836596939116, ordered_statistics=[OrderedStatistic(items_base=frozenset({'canned beer'}), items_add=frozenset({'whole milk'}), confidence=0.1282051282051282, lift=0.8118211313302299)])
RelationRecord(items=frozenset({'whole milk', 'cat food'}), support=0.001670787943594199, ordered_statistics=[OrderedStatistic(items_base=frozenset({'cat food'}), items_add=frozenset({'whole milk'}), confidence=0.14124293785310735, lift=0.8943792124824568)])
RelationRecord(items=frozenset({'whole milk', 'chewing gum'}), support=0.001670787943594199, ordered_statistics=[OrderedStatistic(items_base=frozenset({'chewing gum'}), items_add=frozenset({'whole milk'}), confidence=0.1388888888888889, lift=0.8794728922744158)])
RelationRecord(items=frozenset({'chewing gum', 'yogurt'}), support=0.001403461872619127, ordered_statistics=[OrderedStatistic(items_base=frozenset({'chewing gum'}), items_add=frozenset({'yogurt'}), confidence=0.11666666666666667, lift=1.358508430609598)])
RelationRecord(items=frozenset({'rolls/buns', 'chicken'}), support=0.0028737552629820224, ordered_statistics=[OrderedStatistic(items_base=frozenset({'chicken'}), items_add=frozenset({'rolls/buns'}), confidence=0.10311750599520385, lift=0.9373920062006289)])
RelationRecord(items=frozenset({'whole milk', 'chicken'}), support=0.003408407404932166, ordered_statistics=[OrderedStatistic(items_base=frozenset({'chicken'}), items_add=frozenset({'whole milk'}), confidence=0.1223021582733813, lift=0.774442316650277)])
RelationRecord(items=frozenset({'chocolate', 'rolls/buns'}), support=0.002806923745238254, ordered_statistics=[OrderedStatistic(items_base=frozenset({'chocolate'}), items_add=frozenset({'rolls/buns'}), confidence=0.11898016997167138, lift=1.081591909651348)])
RelationRecord(items=frozenset({'whole milk', 'chocolate'}), support=0.0029405867807257902, ordered_statistics=[OrderedStatistic(items_base=frozenset({'chocolate'}), items_add=frozenset({'whole milk'}), confidence=0.12464589235127478, lift=0.789283320885368)])
RelationRecord(items=frozenset({'whole milk', 'citrus fruit'}), support=0.007150972398583172, ordered_statistics=[OrderedStatistic(items_base=frozenset({'citrus fruit'}), items_add=frozenset({'whole milk'}), confidence=0.13459119496855346, lift=0.8522590140983773)])
RelationRecord(items=frozenset({'whole milk', 'coffee'}), support=0.003809396511394774, ordered_statistics=[OrderedStatistic(items_base=frozenset({'coffee'}), items_add=frozenset({'whole milk'}), confidence=0.12050739957716701, lift=0.7630775369755185)])
RelationRecord(items=frozenset({'whole milk', 'cream cheese '}), support=0.0028737552629820224, ordered_statistics=[OrderedStatistic(items_base=frozenset({'cream cheese '}), items_add=frozenset({'whole milk'}), confidence=0.12146892655367232, lift=0.7691661227349129)])
RelationRecord(items=frozenset({'other vegetables', 'curd'}), support=0.003542070440419702, ordered_statistics=[OrderedStatistic(items_base=frozenset({'curd'}), items_add=frozenset({'other vegetables'}), confidence=0.10515873015873017, lift=0.861242517441204)])
RelationRecord(items=frozenset({'whole milk', 'curd'}), support=0.004143554100113613, ordered_statistics=[OrderedStatistic(items_base=frozenset({'curd'}), items_add=frozenset({'whole milk'}), confidence=0.12301587301587302, lift=0.7789617045859112)])
RelationRecord(items=frozenset({'whole milk', 'dessert'}), support=0.0024059346387756467, ordered_statistics=[OrderedStatistic(items_base=frozenset({'dessert'}), items_add=frozenset({'whole milk'}), confidence=0.1019830028328612, lift=0.645777262542574)])
RelationRecord(items=frozenset({'detergent', 'rolls/buns'}), support=0.0010024727661565194, ordered_statistics=[OrderedStatistic(items_base=frozenset({'detergent'}), items_add=frozenset({'rolls/buns'}), confidence=0.11627906976744186, lift=1.0570374975274803)])
RelationRecord(items=frozenset({'whole milk', 'detergent'}), support=0.001403461872619127, ordered_statistics=[OrderedStatistic(items_base=frozenset({'detergent'}), items_add=frozenset({'whole milk'}), confidence=0.1627906976744186, lift=1.0308240411774547)])
RelationRecord(items=frozenset({'detergent', 'yogurt'}), support=0.0010693042839002875, ordered_statistics=[OrderedStatistic(items_base=frozenset({'detergent'}), items_add=frozenset({'yogurt'}), confidence=0.12403100775193798, lift=1.4442614544686756)])
RelationRecord(items=frozenset({'whole milk', 'domestic eggs'}), support=0.005279689901757669, ordered_statistics=[OrderedStatistic(items_base=frozenset({'domestic eggs'}), items_add=frozenset({'whole milk'}), confidence=0.14234234234234236, lift=0.9013408668931312)])
RelationRecord(items=frozenset({'flour', 'tropical fruit'}), support=0.0010693042839002875, ordered_statistics=[OrderedStatistic(items_base=frozenset({'flour'}), items_add=frozenset({'tropical fruit'}), confidence=0.10958904109589042, lift=1.6171408500175626)])
RelationRecord(items=frozenset({'flour', 'whole milk'}), support=0.0013366303548753592, ordered_statistics=[OrderedStatistic(items_base=frozenset({'flour'}), items_add=frozenset({'whole milk'}), confidence=0.136986301369863, lift=0.8674253184076429)])
RelationRecord(items=frozenset({'other vegetables', 'frankfurter'}), support=0.005146026866270133, ordered_statistics=[OrderedStatistic(items_base=frozenset({'frankfurter'}), items_add=frozenset({'other vegetables'}), confidence=0.13628318584070798, lift=1.1161495948191098)])
RelationRecord(items=frozenset({'whole milk', 'frankfurter'}), support=0.005279689901757669, ordered_statistics=[OrderedStatistic(items_base=frozenset({'frankfurter'}), items_add=frozenset({'whole milk'}), confidence=0.13982300884955753, lift=0.8853879311959075)])
RelationRecord(items=frozenset({'whole milk', 'frozen fish'}), support=0.0010693042839002875, ordered_statistics=[OrderedStatistic(items_base=frozenset({'frozen fish'}), items_add=frozenset({'whole milk'}), confidence=0.15686274509803924, lift=0.9932870312746345)])
RelationRecord(items=frozenset({'other vegetables', 'frozen meals'}), support=0.002138608567800575, ordered_statistics=[OrderedStatistic(items_base=frozenset({'frozen meals'}), items_add=frozenset({'other vegetables'}), confidence=0.12749003984063748, lift=1.0441343547539457)])
RelationRecord(items=frozenset({'whole milk', 'frozen meals'}), support=0.0019381140145692708, ordered_statistics=[OrderedStatistic(items_base=frozenset({'frozen meals'}), items_add=frozenset({'whole milk'}), confidence=0.1155378486055777, lift=0.7316093223382392)])
RelationRecord(items=frozenset({'other vegetables', 'frozen vegetables'}), support=0.003141081333957094, ordered_statistics=[OrderedStatistic(items_base=frozenset({'frozen vegetables'}), items_add=frozenset({'other vegetables'}), confidence=0.11217183770883055, lift=0.9186793692595684)])
RelationRecord(items=frozenset({'whole milk', 'frozen vegetables'}), support=0.003809396511394774, ordered_statistics=[OrderedStatistic(items_base=frozenset({'frozen vegetables'}), items_add=frozenset({'whole milk'}), confidence=0.1360381861575179, lift=0.8614216586859672)])
RelationRecord(items=frozenset({'fruit/vegetable juice', 'rolls/buns'}), support=0.003742564993651006, ordered_statistics=[OrderedStatistic(items_base=frozenset({'fruit/vegetable juice'}), items_add=frozenset({'rolls/buns'}), confidence=0.11001964636542241, lift=1.0001360683874942)])
RelationRecord(items=frozenset({'whole milk', 'fruit/vegetable juice'}), support=0.004410880171088686, ordered_statistics=[OrderedStatistic(items_base=frozenset({'fruit/vegetable juice'}), items_add=frozenset({'whole milk'}), confidence=0.12966601178781928, lift=0.8210717454003978)])
RelationRecord(items=frozenset({'other vegetables', 'grapes'}), support=0.001603956425850431, ordered_statistics=[OrderedStatistic(items_base=frozenset({'grapes'}), items_add=frozenset({'other vegetables'}), confidence=0.1111111111111111, lift=0.9099920939001398)])
RelationRecord(items=frozenset({'whole milk', 'grapes'}), support=0.0019381140145692708, ordered_statistics=[OrderedStatistic(items_base=frozenset({'grapes'}), items_add=frozenset({'whole milk'}), confidence=0.13425925925925924, lift=0.8501571291986019)])
RelationRecord(items=frozenset({'whole milk', 'ham'}), support=0.0027400922274944863, ordered_statistics=[OrderedStatistic(items_base=frozenset({'ham'}), items_add=frozenset({'whole milk'}), confidence=0.16015624999999997, lift=1.0141421789039355)])

**Converting the results into DataFrame**

In [12]:
records = []
for rule in rules:
    for stat in rule.ordered_statistics:
        if len(stat.items_base) == 0:  # skip single-item rules
            continue
        records.append({
            'lhs': tuple(stat.items_base)[0],
            'rhs': tuple(stat.items_add)[0],
            'support': rule.support,
        })

df_rules = pd.DataFrame(records)
df_rules.head(15)

              lhs               rhs   support
0        UHT-milk  other vegetables  0.002139
1        UHT-milk        whole milk  0.002540
2            beef        whole milk  0.004678
3         berries  other vegetables  0.002673
4         berries        whole milk  0.002272
5       beverages  other vegetables  0.001738
6       beverages              soda  0.001871
7       beverages        whole milk  0.001938
8    bottled beer  other vegetables  0.004678
9    bottled beer        whole milk  0.007151
10  bottled water        whole milk  0.007151
11    brown bread        whole milk  0.004478
12         butter        whole milk  0.004678
13          candy        rolls/buns  0.001470
14          candy        whole milk  0.002139

# **Thank You!**